import trafaret as t

from config.config import CONFIGS_BASE_DIR
from config.utils import load_config

REPORT_CONFIG_FILE = 'report_config.yml'
SERVER_CONFIG_FILE = 'server_config.yml'

CONFIG_TRAFARET = t.Dict(
    {
        'DOCKER_ENDPOINT': t.String,
        'DOCKER_IMAGES_INSPECT': t.String,
        'DOCKER_CONTAINERS_INSPECT': t.String,
        'DOCKER_VOLUMES_INSPECT': t.String,
        'DOCKER_NETWORKS_INSPECT': t.String,
        'DOCKER_SYSTEM': t.String,
        'DOCKER_SYSTEM_DF': t.String,
        'DOCKER_SYSTEM_VERSION': t.String,
        'DOCKER_SYSTEM_EVENTS': t.String,
        'DOCKER_PLUGINS_INSPECT': t.String,

        'SWARM_ENDPOINT': t.String,
        'SWARM_SERVICES_INSPECT': t.String,
        'SWARM_TASKS_INSPECT': t.String,
        'SWARM_CONFIGS_INSPECT': t.String,
        'SWARM_SECRETS_INSPECT': t.String,
        'SWARM_NODES_INSPECT': t.String,
    }
)

SERVER_CONFIG_TRAFARET = t.Dict(
    {
        'HOST': t.IP,
        'PORT': t.Int(),
        'RRSSH_PROXY': t.Bool
    }
)

CONF = load_config(
    file=CONFIGS_BASE_DIR / REPORT_CONFIG_FILE,
    config_trafaret=CONFIG_TRAFARET
)

SERVER_CONF = load_config(
    file=CONFIGS_BASE_DIR / SERVER_CONFIG_FILE,
    config_trafaret=SERVER_CONFIG_TRAFARET
)


HOST = SERVER_CONF['HOST']
PORT = SERVER_CONF['PORT']
SERVER_URL = f'http://{HOST}:{PORT}'

DOCKER_ENDPOINT = CONF['DOCKER_ENDPOINT']
IMAGES_INSPECT = CONF['DOCKER_IMAGES_INSPECT']
CONTAINERS_INSPECT = CONF['DOCKER_CONTAINERS_INSPECT']
VOLUMES_INSPECT = CONF['DOCKER_VOLUMES_INSPECT']
NETWORKS_INSPECT = CONF['DOCKER_NETWORKS_INSPECT']
SYSTEM = CONF['DOCKER_SYSTEM']
SYSTEM_DF = CONF['DOCKER_SYSTEM_DF']
SYSTEM_VERSION = CONF['DOCKER_SYSTEM_VERSION']
SYSTEM_EVENTS = CONF['DOCKER_SYSTEM_EVENTS']
PLUGINS_INSPECT = CONF['DOCKER_PLUGINS_INSPECT']

SWARM_ENDPOINT = CONF['SWARM_ENDPOINT']
SERVICES_INSPECT = CONF['SWARM_SERVICES_INSPECT']
TASKS_INSPECT = CONF['SWARM_TASKS_INSPECT']
CONFIGS_INSPECT = CONF['SWARM_CONFIGS_INSPECT']
SECRETS_INSPECT = CONF['SWARM_SECRETS_INSPECT']
NODES_INSPECT = CONF['SWARM_NODES_INSPECT']
