host: 0.0.0.0
port: 8080

ssh_client_remote_host: 127.0.0.1
ssh_client_remote_port: 8022
ssh_server_host_keys_paths: 'key'
ssh_authorized_client_keys_path: 'authorized_keys'
ssh_encoding: 'utf8'
ssh_connection_timeout: 10

uuid: 37bb75c4-1ea3-4294-b2e4-4551a060a801
